// teknav-data.js — Seed data for Teknav publication (ES module)
import { ART1_CONTENT, ART2_CONTENT, ART3_CONTENT } from './article-contents-1.js';
import { ART4_CONTENT, ART5_CONTENT, ART6_CONTENT, ART7_CONTENT, ART8_CONTENT } from './article-contents-2.js';
import { ART9_CONTENT, ART10_CONTENT, ART11_CONTENT, ART12_CONTENT, ART13_CONTENT } from './article-contents-3.js';
import { ART14_CONTENT, ART15_CONTENT, ART16_CONTENT } from './article-contents-4.js';
import { ART17_CONTENT, ART18_CONTENT, ART19_CONTENT } from './article-contents-5.js';
import { ART20_CONTENT, ART27_CONTENT, ART28_CONTENT } from './article-contents-8.js';
import { ART21_CONTENT, ART22_CONTENT, ART23_CONTENT } from './article-contents-7.js';
import { ART24_CONTENT, ART25_CONTENT, ART26_CONTENT } from './article-contents-6.js';
import { ART29_CONTENT } from './article-contents-9.js';
import { ART30_CONTENT, ART31_CONTENT, ART32_CONTENT } from './article-contents-10.js';
import { ART33_CONTENT } from './article-contents-11.js';
import { ART34_CONTENT } from './article-contents-12.js';
import { ART35_CONTENT } from './article-contents-13.js';

export const TeknavData = (() => {

  const categories = [
    { id: 'ai', slug: 'ai', name: 'هوش مصنوعی', color: '#0F6B73', description: 'تحلیل‌های عمیق از پیشرفت‌های هوش مصنوعی و مدل‌های زبانی', articleCount: 9, authorCount: 1, avgReadTime: 13, diagram: 'neural' },
    { id: 'data', slug: 'data', name: 'علم داده', color: '#D49A2A', description: 'تحلیل داده، یادگیری ماشین و مهندسی داده', articleCount: 2, authorCount: 1, avgReadTime: 14, diagram: 'pipeline' },
    { id: 'startup', slug: 'startup', name: 'استارتاپ', color: '#C76D4A', description: 'اکوسیستم نوآوری و تحلیل استارتاپ‌های تکنولوژی', articleCount: 3, authorCount: 1, avgReadTime: 11, diagram: 'growth' },
    { id: 'security', slug: 'security', name: 'امنیت سایبری', color: '#2F8F6B', description: 'تحلیل تهدیدات سایبری و امنیت در دنیای دیجیتال', articleCount: 3, authorCount: 1, avgReadTime: 12, diagram: 'cyber' },
    { id: 'hardware', slug: 'hardware', name: 'سخت‌افزار', color: '#5F6B6D', description: 'بررسی سخت‌افزار و تکنولوژی‌های نوین تراشه', articleCount: 9, authorCount: 1, avgReadTime: 13, diagram: 'chip' },
    { id: 'software', slug: 'software', name: 'نرم‌افزار', color: '#0F6B73', description: 'دنیای توسعه نرم‌افزار و معماری سیستم', articleCount: 5, authorCount: 1, avgReadTime: 12, diagram: 'arch' },
    { id: 'future', slug: 'future', name: 'آینده فناوری', color: '#D49A2A', description: 'نگاهی به تکنولوژی‌های آینده و تغییرات جهان', articleCount: 3, authorCount: 1, avgReadTime: 14, diagram: 'timeline' },
  ];

  const topicHubs = [
    {
      slug: 'ai',
      categorySlug: 'ai',
      title: 'هوش مصنوعی',
      seoTitle: 'هوش مصنوعی | مرجع تحلیل AI، مدل‌های زبانی و عامل‌های هوشمند',
      description: 'قطب تحلیل هوش مصنوعی تکناو؛ از مبانی استدلال مدل‌ها تا پیاده‌سازی عامل‌های هوشمند و آینده AI.',
      intro: 'تکناو در این قطب، عمیق‌ترین تحلیل‌ها را درباره تحول هوش مصنوعی ارائه می‌دهد.',
      keywords: ['هوش مصنوعی', 'AI', 'مدل زبانی', 'Agentic AI', 'یادگیری ماشین'],
      faqs: [
        ['تفاوت هوش مصنوعی با یادگیری ماشین چیست؟', 'یادگیری ماشین زیرمجموعه‌ای از هوش مصنوعی است که روی آموزش مدل از داده تمرکز دارد.'],
        ['آینده هوش مصنوعی به کدام سمت می‌رود؟', 'تمرکز از تولید متن به سمت اجرای وظایف توسط عامل‌های هوشمند (Agents) در حال حرکت است.'],
      ],
    },
    {
      slug: 'security',
      categorySlug: 'security',
      title: 'امنیت سایبری',
      seoTitle: 'امنیت سایبری | راهنمای جامع امنیت ابری، LLM Security و دفاع دیجیتال',
      description: 'مرکز تحلیل امنیت سایبری تکناو؛ بررسی تهدیدات مدرن، امنیت هوش مصنوعی و پروتکل‌های حفاظتی.',
      intro: 'امنیت در دنیای دیجیتال یک انتخاب نیست، یک ضرورت است. تکناو در این بخش به تحلیل عمیق این حوزه می‌پردازد.',
      keywords: ['امنیت سایبری', 'امنیت اطلاعات', 'حملات سایبری', 'LLM Security', 'دفاع ابری'],
      faqs: [
        ['امنیت هوش مصنوعی شامل چه مواردی است؟', 'از prompt injection تا امنیت زنجیره تامین مدل‌های هوشمند.'],
        ['چطور در برابر حملات سایبری ایمن بمانیم؟', 'با استفاده از راهکارهای دفاعی مدرن و آموزش مداوم تیم‌های امنیتی.'],
      ],
    },
    {
      slug: 'software',
      categorySlug: 'software',
      title: 'نرم‌افزار',
      seoTitle: 'نرم‌افزار | معماری سیستم، مهندسی نرم‌افزار و توسعه مدرن',
      description: 'قطب نرم‌افزار تکناو؛ از بررسی معماری میکروسرویس تا جدیدترین فریم‌ورک‌ها و زبان‌های برنامه‌نویسی.',
      intro: 'توسعه نرم‌افزار قلب تپنده دنیای دیجیتال است. ما در تکناو به تحلیل دقیق این صنعت می‌پردازیم.',
      keywords: ['نرم‌افزار', 'معماری نرم‌افزار', 'برنامه‌نویسی', 'توسعه وب', 'میکروسرویس'],
      faqs: [
        ['معماری میکروسرویس برای چه پروژه‌هایی مناسب است؟', 'برای پروژه‌های بزرگ و مقیاس‌پذیر که نیاز به توسعه مستقل تیم‌ها دارند.'],
      ],
    },
    {
      slug: 'hardware',
      categorySlug: 'hardware',
      title: 'سخت‌افزار',
      seoTitle: 'سخت‌افزار | پردازنده‌های هوش مصنوعی، کوانتوم و رباتیک',
      description: 'قطب سخت‌افزار تکناو؛ از تحلیل معماری Blackwell تا تراشه‌های کوانتومی و ربات‌های انسان‌نما.',
      intro: 'سیلیکون و فلز در حال هوشمند شدن هستند. تکناو در این بخش به کالبدشکافی سخت‌افزارهای فردا می‌پردازد.',
      keywords: ['سخت‌افزار', 'تراشه', 'GPU', 'رباتیک', 'کوانتوم'],
      faqs: [
        ['آینده پردازنده‌های گرافیکی به کدام سمت می‌رود؟', 'تمرکز از قدرت خام به سمت پهنای باند حافظه (HBM4) و بهینه‌سازی استنتاج تغییر یافته است.'],
      ],
    },
    {
      slug: 'startup',
      categorySlug: 'startup',
      title: 'استارتاپ',
      seoTitle: 'استارتاپ | تحلیل اکوسیستم نوآوری، سرمایه‌گذاری و تکنولوژی‌های رشد',
      description: 'قطب استارتاپ تکناو؛ بررسی چالش‌های مقیاس‌پذیری، جذب سرمایه در هوش مصنوعی و اقتصاد دیجیتال.',
      intro: 'ساختن آینده کار آسانی نیست. ما در تکناو مسیر رشد و چالش‌های استارتاپ‌های تکنولوژی را تحلیل می‌کنیم.',
      keywords: ['استارتاپ', 'نوآوری', 'سرمایه‌گذاری', 'VC', 'اقتصاد دیجیتال'],
      faqs: [
        ['چطور یک استارتاپ را در شرایط محدودیت مقیاس‌پذیر کنیم؟', 'با استفاده از معماری‌های فوق‌تاب‌آور و تمرکز بر بهره‌وری منابع.'],
      ],
    },
    {
      slug: 'data',
      categorySlug: 'data',
      title: 'علم داده',
      seoTitle: 'علم داده | مهندسی داده، تحلیل و یادگیری ماشین',
      description: 'قطب علم داده تکناو؛ از پالایش داده‌های کثیف تا معماری پایگاه‌داده‌های برداری و حاکمیت داده.',
      intro: 'داده‌ها زبان جدید جهان هستند. تکناو به شما کمک می‌کند تا این زبان را به درستی درک و مدیریت کنید.',
      keywords: ['علم داده', 'داده', 'تحلیل داده', 'مهندسی داده', 'پایگاه داده'],
      faqs: [
        ['چرا داده‌های پاک برای هوش مصنوعی حیاتی هستند؟', 'چون کیفیت خروجی هر مدلی مستقیماً به کیفیت و خلوص داده‌های ورودی وابسته است.'],
      ],
    },
  ];

  const tags = [
    'یادگیری ماشین', 'هوش مصنوعی', 'GPT', 'علم داده', 'امنیت', 'تکنولوژی',
    'مدل زبانی', 'استارتاپ', 'داده', 'نوآوری', 'آینده', 'نرم‌افزار',
    'برنامه‌نویسی', 'امنیت سایبری', 'دنیای دیجیتال', 'رباتیک', 'تراشه',
    'RISC-V', 'GPU', 'LLM', 'RAG', 'هوش مصنوعی عاملی', 'اینترنت اشیا', 'رایانش ابری',
    'فناوری نوظهور', 'تحلیل فناوری', 'AI Agents', 'Agentic AI', 'توسعه‌دهنده'
  ].map((name, i) => ({ id: i + 1, name, count: Math.floor(Math.random() * 30) + 5 }));

  const glossary = [
    { slug: 'ai', term: 'هوش مصنوعی', english: 'Artificial Intelligence', summary: 'هوش مصنوعی مجموعه‌ای از روش‌هاست که به نرم‌افزار امکان تشخیص الگو، پیش‌بینی، تولید محتوا یا تصمیم‌سازی را می‌دهد.', topic: 'ai', related: ['llm', 'rag', 'agentic-ai'], faqs: [['هوش مصنوعی چه تفاوتی با یادگیری ماشین دارد؟', 'یادگیری ماشین یکی از زیرشاخه‌های هوش مصنوعی است و روی آموزش مدل از داده تمرکز دارد.'], ['چرا هوش مصنوعی برای کسب‌وکار مهم است؟', 'چون می‌تواند فرایندهای تکراری، تحلیل داده و تجربه کاربر را سریع‌تر و دقیق‌تر کند.']] },
    { slug: 'llm', term: 'مدل زبانی بزرگ', english: 'Large Language Model', summary: 'مدل زبانی بزرگ روی حجم وسیعی از متن آموزش دیده و می‌تواند متن را بفهمد، خلاصه کند، تولید کند یا به پرسش‌ها پاسخ دهد.', topic: 'ai', related: ['ai', 'rag', 'prompt-injection'], faqs: [['LLM همیشه پاسخ درست می‌دهد؟', 'خیر. خروجی آن باید با منبع معتبر، ارزیابی و کنترل انسانی بررسی شود.'], ['کاربرد اصلی LLM چیست؟', 'جست‌وجوی معنایی، پشتیبانی، تولید پیش‌نویس، تحلیل متن و ساخت دستیارهای نرم‌افزاری.']] },
    { slug: 'rag', term: 'تولید تقویت‌شده با بازیابی', english: 'Retrieval-Augmented Generation', summary: 'RAG پیش از تولید پاسخ، اسناد مرتبط را بازیابی می‌کند تا خروجی مدل به داده‌های واقعی و به‌روز متصل شود.', topic: 'data', related: ['ai', 'llm', 'vector-database'], faqs: [['RAG جایگزین آموزش مدل است؟', 'نه؛ برای بسیاری از کاربردها راهی کم‌هزینه‌تر برای اتصال مدل به دانش اختصاصی است.'], ['ریسک اصلی RAG چیست؟', 'کیفیت پایین داده، بازیابی اشتباه و نبود ارزیابی منظم می‌تواند پاسخ را ضعیف کند.']] },
    { slug: 'prompt-injection', term: 'تزریق پرامپت', english: 'Prompt Injection', summary: 'تزریق پرامپت حمله‌ای است که تلاش می‌کند دستورهای پنهان یا مخرب را وارد ورودی مدل کند و رفتار سیستم را تغییر دهد.', topic: 'security', related: ['llm', 'rag'], faqs: [['تزریق پرامپت فقط در چت‌بات‌ها رخ می‌دهد؟', 'خیر. هر سامانه‌ای که خروجی مدل را به ابزار، داده یا اقدام متصل کند در معرض این ریسک است.'], ['چطور کنترل می‌شود؟', 'با جداسازی داده از دستور، محدودکردن ابزارها، ثبت لاگ، ارزیابی و بازبینی انسانی.']] },
    { slug: 'vector-database', term: 'پایگاه داده برداری', english: 'Vector Database', summary: 'پایگاه داده برداری داده‌ها را به بردارهای عددی تبدیل و برای جست‌وجوی معنایی، شباهت و بازیابی در سامانه‌های هوش مصنوعی استفاده می‌کند.', topic: 'data', related: ['rag', 'llm'], faqs: [['چه زمانی به پایگاه داده برداری نیاز داریم؟', 'وقتی جست‌وجوی کلیدواژه کافی نیست و باید شباهت معنایی بین متن، تصویر یا سند پیدا شود.'], ['آیا همیشه لازم است؟', 'نه؛ برای داده کم یا جست‌وجوی ساده، روش‌های سنتی ممکن است کافی باشند.']] },
    { slug: 'agentic-ai', term: 'هوش مصنوعی عاملی', english: 'Agentic AI', summary: 'هوش مصنوعی عاملی به سامانه‌هایی گفته می‌شود که هدف را به گام‌ها تقسیم می‌کنند، ابزار انتخاب می‌کنند و با کنترل مشخص اقدام انجام می‌دهند.', topic: 'ai', related: ['ai', 'llm', 'prompt-injection'], faqs: [['عامل هوش مصنوعی با چت‌بات چه فرق دارد؟', 'عامل فقط پاسخ نمی‌دهد؛ می‌تواند برنامه‌روزی کند و در محدوده مجاز ابزار اجرا کند.'], ['چالش اصلی Agentic AI چیست؟', 'کنترل دسترسی، مشاهده‌پذیری، ارزیابی خروجی و جلوگیری از اقدام اشتباه.']] },
  ];

  const authors = [
    {
      id: 'a1',
      name: 'آرسام صباغ',
      slug: 'sabbagh',
      username: 'arsam-sabbagh',
      specialty: 'پژوهشگر ارشد هوش مصنوعی و مهندسی داده',
      articleCount: 24,
      bio: 'آرسام صباغ پژوهشگر ارشد هوش مصنوعی و سردبیر تکنّاو است. او بیش از سه سال تجربه در یادگیری ماشین، مهندسی داده، و استقرار سیستم‌های هوشمند در مقیاس صنعتی دارد. تخصص اصلی او طراحی پایپ‌لاین‌های داده برای مدل‌های زبانی بزرگ (LLM)، بهینه‌سازی استنتاج (Inference Optimization) و ارزیابی کمّی مدل‌های مرزی (Frontier Models) است. آرسام پیش از تأسیس تکنّاو، در چندین شرکت حوزه فناوری به عنوان محقق و مهندس ارشد فعالیت داشته و مقالات فنی او در حوزه‌های داده-محوری، ایمنی هوش مصنوعی و سیستم‌های عاملی مرجع بسیاری از تیم‌های مهندسی فارسی‌زبان است.',
      expertise: ['یادگیری ماشین', 'LLM', 'مهندسی داده', 'استنتاج مدل', 'هوش مصنوعی داده‌محور', 'سیستم‌های عاملی'],
      education: 'مهندسی کامپیوتر — گرایش هوش مصنوعی',
      social: { twitter: 'https://x.com/teknavir', linkedin: 'https://linkedin.com/company/teknav', github: '#' },
      initials: 'آ',
      color: '#0F6B73',
      verifiedExpert: true,
      verificationNote: 'پژوهشگر ارشد هوش مصنوعی با بیش از ۳ سال تجربه در مهندسی LLM و سیستم‌های داده‌محور',
      joinedDate: '2023-09-01',
    },
    {
      id: 'a2',
      name: 'سیداحمدرضا محجوب',
      slug: 'mahjoob',
      username: 'ahmadreza-mahjoub',
      specialty: 'تحلیلگر ارشد امنیت سایبری و هوش مصنوعی',
      articleCount: 7,
      bio: 'سیداحمدرضا محجوب تحلیلگر ارشد امنیت سایبری و از نویسندگان اصلی تکنّاو در حوزه تهدیدات دیجیتال است. تخصص اصلی او تحلیل آسیب‌پذیری‌های Zero-Day، امنیت زیرساخت‌های ابری، و بررسی تقاطع هوش مصنوعی و امنیت سایبری است. احمدرضا با رویکردی دقیق و فنی، پیچیده‌ترین حملات و بردارهای نفوذ را برای مخاطبان فارسی‌زبان تشریح می‌کند؛ از تحلیل بدافزارهای پیشرفته (APT) تا بررسی تأثیر AI بر اتوماسیون حملات سایبری. او پیش از تکنّاو، سابقه همکاری با تیم‌های Red Team و تحلیل تهدید در سازمان‌های امنیتی را دارد.',
      expertise: ['امنیت سایبری', 'Zero-Day Research', 'تحلیل APT', 'امنیت ابری', 'هوش مصنوعی در امنیت', 'رمزنگاری پس‌کوانتومی'],
      education: 'مهندسی شبکه و امنیت اطلاعات',
      social: { twitter: 'https://x.com/teknavir', linkedin: 'https://linkedin.com/company/teknav', github: '#' },
      initials: 'س',
      color: '#2F8F6B',
      verifiedExpert: true,
      verificationNote: 'تحلیلگر امنیت سایبری با تخصص در Zero-Day Research و تهدیدات APT',
      joinedDate: '2023-10-15',
    },
    {
      id: 'a3',
      name: 'رادمان قلیچی',
      slug: 'radman-ghelichi',
      username: 'radman-ghelichi',
      specialty: 'استراتژیست فناوری و تحلیلگر اکوسیستم نوآوری',
      articleCount: 3,
      bio: 'رادمان قلیچی استراتژیست فناوری و تحلیلگر اکوسیستم استارتاپ و سرمایه‌گذاری خطرپذیر در تکنّاو است. او با نگاهی کلان به ترندهای بلندمدت فناوری، تأثیر نوآوری بر مدل‌های کسب‌وکار، و مسیر رشد شرکت‌های فناور می‌پردازد. تخصص رادمان در تحلیل موج‌های سرمایه‌گذاری در هوش مصنوعی، ارزیابی اکوسیستم استارتاپ‌های ایرانی و منطقه‌ای، و تبیین استراتژی‌های رقابتی شرکت‌های فناوری جهانی است. او پیش از تکنّاو، به عنوان مشاور استراتژی با چندین استارتاپ مرحله رشد (Growth Stage) همکاری داشته است.',
      expertise: ['استراتژی فناوری', 'سرمایه‌گذاری VC', 'اکوسیستم استارتاپ', 'تحلیل بازار', 'نوآوری باز', 'استارتاپ‌های ایرانی'],
      education: 'مدیریت استراتژیک فناوری',
      social: { twitter: 'https://x.com/teknavir', linkedin: 'https://linkedin.com/company/teknav', github: '#' },
      initials: 'ر',
      color: '#C76D4A',
      verifiedExpert: true,
      verificationNote: 'استراتژیست فناوری با تمرکز بر اکوسیستم استارتاپ و سرمایه‌گذاری در حوزه هوش مصنوعی',
      joinedDate: '2024-01-10',
    },
  ];

  const articles = [
    {
      id: 'art35',
      slug: 'mcp-model-context-protocol-2026',
      title: 'از چت‌بات تا دستیار واقعی: پروتکل MCP چطور هوش مصنوعی را به ابزارهای روزمره وصل کرد',
      subtitle: 'کالبدشکافی پروتکل استانداردی که ChatGPT، Gemini و همه‌ی مدل‌های بزرگ دنیا آن را پذیرفتند',
      summary: 'پروتکل MCP یا Model Context Protocol، استانداردی است که هوش مصنوعی را از یک چت‌بات ساده به دستیاری تبدیل می‌کند که می‌تواند به ایمیل، پایگاه داده، فایل‌ها و سرویس‌های واقعی دسترسی داشته باشد. تحلیل فنی معماری، امنیت، و اکوسیستم جهانی که بر این پروتکل شرط‌بندی کرده است.',
      category: 'ai',
      categoryName: 'هوش مصنوعی',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۱۶',
      dateEn: '2026-05-06',
      readTime: 14,
      type: 'تحلیل عمیق',
      status: 'منتشرشده',
      featured: false,
      tags: ['MCP', 'Model Context Protocol', 'هوش مصنوعی عاملی', 'ChatGPT', 'Function Calling', 'Agentic AI', 'پروتکل', 'هوش مصنوعی', 'دستیار هوشمند'],
      diagram: 'arch',
      views: 1840,
      reactions: 124,
      content: ART35_CONTENT,
      metaDescription: 'تحلیل فنی عمیق پروتکل MCP (Model Context Protocol): معماری کلاینت-سرور، سه ستون Tools/Resources/Prompts، تفاوت با Function Calling، امنیت MCP، و اکوسیستم ۲۰۲۶ از Claude تا OpenAI. راهنمای جامع فارسی MCP.',
      keywords: ['MCP چیست', 'Model Context Protocol', 'پروتکل MCP', 'هوش مصنوعی عاملی', 'Claude MCP', 'Cursor MCP', 'Function Calling', 'JSON-RPC', 'Agentic AI', 'اتصال هوش مصنوعی به ابزار', 'سرور MCP', 'اینترنت عاملی'],
      canonicalPath: '/article/mcp-model-context-protocol-2026',
      ogImage: '/images/og/agentic-ai-production-2026.jpg',
      factCheckedAt: '2026-05-06',
    },
    {
      id: 'art34',
      slug: 'ai-data-centric-2026',
      title: 'هوش مصنوعی داده‌محور ۲۰۲۶: وقتی قانون مقیاس‌گذاری به بن‌بست رسید',
      subtitle: 'از فروپاشی مدل تا مهندسی هوشمندی؛ چرا کیفیت داده از معماری مدل مهم‌تر شده است',
      summary: 'در سال ۲۰۲۶، قانون مقیاس‌گذاری به دیوار سختی برخورده است. مهندسی کیفیت داده جایگزین مهندسی معماری مدل شده؛ تحلیل عمیق فنی از بحران Model Collapse، Semantic Layers، Data Provenance و اقتصاد داده‌های قابل اعتماد.',
      category: 'ai',
      categoryName: 'هوش مصنوعی',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۱۵',
      dateEn: '2026-05-05',
      readTime: 13,
      type: 'تحلیل عمیق',
      status: 'منتشرشده',
      featured: true,
      tags: ['هوش مصنوعی', 'Data-Centric AI', 'Model Collapse', 'Data Governance', 'LLM', 'داده', 'مهندسی هوشمندی'],
      diagram: 'neural',
      views: 3210,
      reactions: 187,
      content: ART34_CONTENT,
      metaDescription: 'تحلیل عمیق فنی بحران داده در هوش مصنوعی ۲۰۲۶: چرا قانون مقیاس‌گذاری به بن‌بست رسید؟ بررسی فروپاشی مدل (Model Collapse)، Data-Centric AI، لایه‌های معنایی، اثبات اصالت داده و اقتصاد داده‌های قابل اعتماد برای سیستم‌های عاملی.',
      keywords: ['Data-Centric AI', 'Model Collapse', 'فروپاشی مدل', 'Data Provenance', 'Semantic Layer', 'Data Governance', 'هوش مصنوعی ۲۰۲۶', 'مهندسی هوشمندی', 'قانون مقیاس‌گذاری', 'داده‌های قابل اعتماد', 'EU AI Act'],
      canonicalPath: '/article/ai-data-centric-2026',
      ogImage: '/images/og/data-governance-2026.jpg',
      factCheckedAt: '2026-05-05',
    },
    {
      id: 'art33',
      slug: 'cve-2026-41940-cpanel-zero-day-analysis',
      title: 'تحلیل فنی Zero-Day جدید سی‌پنل (CVE-2026-41940): دسترسی روت بدون احراز هویت',
      subtitle: 'چگونه یک آسیب‌پذیری تزریق CRLF ساده منجر به دسترسی روت در ۱.۵ میلیون سرور لینوکسی شد؟',
      summary: 'بررسی عمیق و فنی آسیب‌پذیری بحرانی CVE-2026-41940 در cPanel که به مهاجمان اجازه می‌دهد با دور زدن مکانیزم لاگین، به دسترسی روت سرور دست پیدا کنند.',
      category: 'security',
      categoryName: 'امنیت سایبری',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۱۳',
      dateEn: '2026-05-03',
      readTime: 12,
      type: 'تحلیل امنیتی',
      status: 'منتشرشده',
      featured: true,
      tags: ['Zero-Day', 'cPanel', 'CVE-2026-41940', 'آسیب‌پذیری', 'لینوکس'],
      diagram: 'cyber',
      views: 12450,
      reactions: 890,
      metaDescription: 'بررسی عمیق و فنی آسیب‌پذیری بحرانی CVE-2026-41940 در cPanel که به مهاجمان اجازه می‌دهد با دور زدن مکانیزم لاگین، به دسترسی روت (Root) سرور دست پیدا کنند.',
      keywords: ['CVE-2026-41940', 'cPanel Zero-Day', 'تزریق CRLF', 'امنیت سرور لینوکس', 'آسیب‌پذیری وب سرور', 'دسترسی روت cPanel', 'WHM Exploit'],
      content: ART33_CONTENT,
      canonicalPath: '/article/cve-2026-41940-cpanel-zero-day-analysis',
      ogImage: '/images/og/cve-2026-41940-cpanel-zero-day-analysis.jpg',
      factCheckedAt: '2026-05-03',
    },
    {
      id: 'art1',
      slug: 'ai-clean-data',
      title: 'نقش داده‌های پاک در موفقیت هوش مصنوعی',
      subtitle: 'چرا کیفیت داده از مدل مهم‌تر است؟',
      summary: 'بدون داده‌های باکیفیت، پیشرفته‌ترین مدل‌های هوش مصنوعی هم شکست خواهند خورد.',
      category: 'ai',
      categoryName: 'هوش مصنوعی',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۰۹',
      dateEn: '2026-04-30',
      readTime: 9,
      type: 'تحلیل عمیق',
      status: 'منتشرشده',
      featured: true,
      tags: ['هوش مصنوعی', 'LLM', 'علم داده'],
      diagram: 'pipeline',
      views: 8420,
      reactions: 312,
      content: ART1_CONTENT,
      metaDescription: 'تحلیل عمیق نقش داده‌های پاک در موفقیت هوش مصنوعی. چرا کیفیت داده‌ها از معماری مدل‌های LLM حیاتی‌تر است؟ بررسی بحران داده در سال ۲۰۲۶.',
      keywords: ['هوش مصنوعی', 'داده پاک', 'آموزش مدل', 'LLM', 'علم داده'],
      canonicalPath: '/article/ai-clean-data',
      ogImage: '/images/og/ai-clean-data.jpg',
      factCheckedAt: '2026-04-30',
      sourceNotes: 'تحقیقات داخلی تکناو و گزارش‌های سالانه MIT AI Lab',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art2',
      slug: 'custom-ai-chips',
      title: 'تراشه‌های سفارشی هوش مصنوعی: پایان عصر پردازنده‌های عمومی',
      subtitle: 'چرا غول‌های فناوری به ساخت سیلیکون‌های اختصاصی روی آورده‌اند؟',
      summary: 'از GB200 انویدیا تا TPU گوگل؛ رقابت بر سر بهینه‌ترین تراشه هوش مصنوعی.',
      category: 'hardware',
      categoryName: 'سخت‌افزار',
      authorId: 'a3',
      authorName: 'رادمان قلیچی',
      authorUsername: 'radman-ghelichi',
      date: '۱۴۰۵/۰۱/۲۵',
      dateEn: '2026-04-14',
      readTime: 12,
      type: 'گزارش تحلیلی',
      status: 'منتشرشده',
      featured: false,
      tags: ['سخت‌افزار', 'GPU', 'تراشه', 'GB200'],
      diagram: 'chip',
      views: 4500,
      reactions: 120,
      content: ART2_CONTENT,
      metaDescription: 'کالبدشکافی تراشه‌های سفارشی هوش مصنوعی در سال ۲۰۲۶. بررسی معماری NVIDIA GB200 و استراتژی سیلیکون‌های اختصاصی گوگل و آمازون.',
      keywords: ['تراشه هوش مصنوعی', 'NVIDIA', 'GB200', 'سخت‌افزار', 'سیلیکون اختصاصی'],
      canonicalPath: '/article/custom-ai-chips',
      ogImage: '/images/og/custom-ai-chips.jpg',
      factCheckedAt: '2026-04-14',
      sourceNotes: 'گزارش‌های زنجیره تامین نیمه‌هادی در تایوان و کوالکام',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art3',
      slug: 'browser-architecture',
      title: 'معماری مدرن مرورگرها: وقتی وب به یک سیستم‌عامل تبدیل می‌شود',
      subtitle: 'نقش WebAssembly و WebGPU در تحول مرورگرهای ۲۰۲۶',
      summary: 'اجرای مدل‌های هوشمند و برنامه‌های سنگین مستقیماً در مرورگر شما.',
      category: 'software',
      categoryName: 'نرم‌افزار',
      authorId: 'a2',
      authorName: 'سیداحمدرضا محجوب',
      authorUsername: 'ahmadreza-mahjoub',
      date: '۱۴۰۵/۰۱/۲۰',
      dateEn: '2026-04-09',
      readTime: 14,
      type: 'آموزشی',
      status: 'منتشرشده',
      featured: false,
      tags: ['نرم‌افزار', 'معماری وب', 'WebAssembly'],
      diagram: 'arch',
      views: 3800,
      reactions: 95,
      content: ART3_CONTENT,
      metaDescription: 'تحلیل معماری نوین مرورگرها در سال ۱۴۰۵. بررسی تاثیر WebAssembly و WebGPU در تبدیل مرورگر به سیستم‌عامل اجرای اپلیکیشن‌های سنگین.',
      keywords: ['معماری مرورگر', 'WebAssembly', 'WebGPU', 'توسعه وب', 'نرم‌افزار'],
      canonicalPath: '/article/browser-architecture',
      ogImage: '/images/og/browser-architecture.jpg',
      factCheckedAt: '2026-04-09',
      sourceNotes: 'مستندات W3C و نقشه‌راه مرورگر کروم ۲۰۲۶',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art4',
      slug: 'software-supply-chain',
      title: 'امنیت زنجیره تأمین نرم‌افزار: نبرد در رگ‌های کد',
      subtitle: 'چطور SBOMهای زنده و استاندارد VEX امنیت ۲۰۲۶ را تغییر می‌دهند؟',
      summary: 'مهاجمان دیگر به درهای بسته حمله نمی‌کنند؛ آن‌ها وارد مواد اولیه نرم‌افزار می‌شوند.',
      category: 'security',
      categoryName: 'امنیت سایبری',
      authorId: 'a2',
      authorName: 'سیداحمدرضا محجوب',
      authorUsername: 'ahmadreza-mahjoub',
      date: '۱۴۰۵/۰۱/۱۵',
      dateEn: '2026-04-04',
      readTime: 11,
      type: 'تحلیل امنیتی',
      status: 'منتشرشده',
      featured: false,
      tags: ['امنیت', 'Open Source', 'SBOM', 'VEX'],
      diagram: 'cyber',
      views: 2900,
      reactions: 70,
      content: ART4_CONTENT,
      metaDescription: 'راهنمای جامع امنیت زنجیره تامین نرم‌افزار. بررسی استانداردهای SBOM و VEX در سال ۲۰۲۶ برای مقابله با حملات نفوذ به رگ‌های کد.',
      keywords: ['امنیت نرم‌افزار', 'زنجیره تامین', 'SBOM', 'VEX', 'امنیت سایبری'],
      canonicalPath: '/article/software-supply-chain',
      ogImage: '/images/og/software-supply-chain.jpg',
      factCheckedAt: '2026-04-04',
      sourceNotes: 'گزارش سالانه امنیت OpenSSF و بنیاد لینوکس',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art5',
      slug: 'iranian-startups-scale',
      title: 'چالش‌های مقیاس‌پذیری استارتاپ‌های ایرانی در عصر محدودیت',
      subtitle: 'بقای فنی در شرایط ناپایداری زیرساخت و مهاجرت نخبگان',
      summary: 'هنر مقیاس‌گذاری در ایران؛ جایی که معماری‌های فوق‌تاب‌آور حرف اول را می‌زنند.',
      category: 'startup',
      categoryName: 'استارتاپ',
      authorId: 'a3',
      authorName: 'رادمان قلیچی',
      authorUsername: 'radman-ghelichi',
      date: '۱۴۰۵/۰۱/۱۰',
      dateEn: '2026-03-30',
      readTime: 10,
      type: 'گزارش ویژه',
      status: 'منتشرشده',
      featured: true,
      tags: ['استارتاپ', 'مقیاس‌پذیری', 'زیرساخت', 'ایران'],
      diagram: 'growth',
      views: 5200,
      reactions: 180,
      content: ART5_CONTENT,
      metaDescription: 'تحلیل چالش‌های فنی و اقتصادی مقیاس‌پذیری استارتاپ‌های ایرانی در سال ۱۴۰۵؛ از تاب‌آوری زیرساخت، هزینه ابر و مهاجرت نخبگان تا معماری‌های بقا در شرایط محدودیت.',
      keywords: ['استارتاپ ایران', 'مقیاس‌پذیری', 'اکوسیستم فناوری', 'زیرساخت', 'نظام صنفی رایانه‌ای'],
      canonicalPath: '/article/iranian-startups-scale',
      ogImage: '/images/og/iranian-startups-scale.jpg',
      factCheckedAt: '2026-03-30',
      sourceNotes: 'مصاحبه با معماران فنی برتر استارتاپ‌های ایرانی',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art6',
      slug: 'small-llms',
      title: 'مدل‌های زبانی کوچک (SLM): وقتی کوچک‌تر، هوشمندتر است',
      subtitle: 'بررسی Phi-4 و Llama 4 Scout؛ انقلاب هوش مصنوعی محلی',
      summary: 'چرا در سال ۱۴۰۵، شرکت‌ها به جای مدل‌های غول‌آسا به مدل‌های کوچک روی آورده‌اند؟',
      category: 'ai',
      categoryName: 'هوش مصنوعی',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۱/۰۵',
      dateEn: '2026-03-25',
      readTime: 13,
      type: 'بررسی فنی',
      status: 'منتشرشده',
      featured: false,
      tags: ['هوش مصنوعی', 'LLM', 'SLM', 'Llama 4'],
      diagram: 'diagram-06',
      views: 6100,
      reactions: 210,
      content: ART6_CONTENT,
      metaDescription: 'تحلیل ظهور مدل‌های زبانی کوچک (SLM) در سال ۲۰۲۶. بررسی عملکرد Phi-4 و Llama 4 Scout در پردازش‌های بومی و کاهش هزینه‌های استنتاج.',
      keywords: ['SLM', 'Llama 4 Scout', 'Phi-4', 'هوش مصنوعی محلی', 'مدل زبانی کوچک'],
      canonicalPath: '/article/small-llms',
      ogImage: '/images/og/small-llms.jpg',
      factCheckedAt: '2026-03-25',
      sourceNotes: 'گزارش فنی Microsoft Research و Meta AI',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art7',
      slug: 'edge-computing',
      title: 'رایانش لبه‌ای: خروج هوش مصنوعی از مرکز به لبه شبکه',
      subtitle: 'نقش تراشه‌های نسل جدید و WebGPU در پردازش‌های محلی',
      summary: 'در سال ۲۰۲۶، دستگاه‌های ما به قدری هوشمند شده‌اند که ابر فقط برای هماهنگی است.',
      category: 'hardware',
      categoryName: 'سخت‌افزار',
      authorId: 'a3',
      authorName: 'رادمان قلیچی',
      authorUsername: 'radman-ghelichi',
      date: '۱۴۰۴/۱۲/۲۵',
      dateEn: '2026-03-16',
      readTime: 12,
      type: 'تحلیل آینده',
      status: 'منتشرشده',
      featured: false,
      tags: ['Edge Computing', 'IoT', 'سخت‌افزار', 'WebGPU'],
      diagram: 'cloud',
      views: 3400,
      reactions: 85,
      content: ART7_CONTENT,
      metaDescription: 'بررسی آینده رایانش لبه‌ای (Edge Computing) در سال ۱۴۰۵. چطور ترکیب تراشه‌های NPU و WebGPU نیاز به پردازش ابری را به حداقل رسانده است؟',
      keywords: ['رایانش لبه‌ای', 'Edge AI', 'IoT', 'WebGPU', 'سخت‌افزار'],
      canonicalPath: '/article/edge-computing',
      ogImage: '/images/og/edge-computing.jpg',
      factCheckedAt: '2026-03-16',
      sourceNotes: 'تحلیل بازار Gartner و استانداردهای IEEE 2026',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art8',
      slug: 'synthetic-data',
      title: 'داده‌های مصنوعی: نجات‌بخش یا قاتل هوش مصنوعی؟',
      subtitle: 'بررسی بحران فروپاشی مدل (Model Collapse) و راهکارهای عبور از آن',
      summary: 'با اتمام داده‌های انسانی، آیا هوش مصنوعی در حلقه‌ی تکرار خود غرق می‌شود؟',
      category: 'data',
      categoryName: 'علم داده',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۴/۱۲/۱۵',
      dateEn: '2026-03-06',
      readTime: 15,
      type: 'تحلیل عمیق',
      status: 'منتشرشده',
      featured: true,
      tags: ['علم داده', 'Synthetic Data', 'مدل زبانی', 'Data Wall'],
      diagram: 'database',
      views: 4700,
      reactions: 140,
      content: ART8_CONTENT,
      metaDescription: 'تحلیل بحران داده‌های انسانی و نقش داده‌های مصنوعی در سال ۲۰۲۶. بررسی پدیده Model Collapse و راهکارهای مهندسی برای حفظ کیفیت LLMها.',
      keywords: ['داده مصنوعی', 'Synthetic Data', 'Model Collapse', 'علم داده', 'آموزش هوش مصنوعی'],
      canonicalPath: '/article/synthetic-data',
      ogImage: '/images/og/synthetic-data.jpg',
      factCheckedAt: '2026-03-06',
      sourceNotes: 'پژوهش‌های دانشگاه استنفورد و DeepMind',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art9',
      slug: 'ai-hardware-roadmap',
      title: 'نقشه راه سخت‌افزار هوش مصنوعی: از Blackwell تا Vera Rubin',
      subtitle: 'تحلیل معماری تراشه‌های ۲۰۲۶ و پایان دیوار حافظه',
      summary: 'انویدیا با Rubin قوانین بازی را تغییر می‌دهد؛ بررسی حافظه‌های HBM4 و پردازنده Vera.',
      category: 'hardware',
      categoryName: 'سخت‌افزار',
      authorId: 'a3',
      authorName: 'رادمان قلیچی',
      authorUsername: 'radman-ghelichi',
      date: '۱۴۰۴/۱۲/۰۵',
      dateEn: '2026-02-24',
      readTime: 12,
      type: 'تحلیل عمیق',
      status: 'منتشرشده',
      featured: false,
      tags: ['سخت‌افزار', 'NVIDIA', 'Rubin', 'HBM4'],
      diagram: 'timeline',
      views: 4100,
      reactions: 110,
      content: ART9_CONTENT,
      metaDescription: 'بررسی نقشه راه سخت‌افزارهای هوش مصنوعی در سال ۲۰۲۶. تحلیل معماری جدید Rubin انویدیا و تاثیر حافظه‌های HBM4 بر سرعت پردازش مدل‌های تریلیونی.',
      keywords: ['سخت‌افزار هوش مصنوعی', 'NVIDIA Rubin', 'HBM4', 'تراشه', 'معماری Blackwell'],
      canonicalPath: '/article/ai-hardware-roadmap',
      ogImage: '/images/og/ai-hardware-roadmap.jpg',
      factCheckedAt: '2026-02-24',
      sourceNotes: 'اطلاعات فنی منتشر شده در GTC 2026',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art10',
      slug: 'quantum-computing',
      title: 'رایانش کوانتومی ۲۰۲۶: عصر کوبیت‌های منطقی و اصلاح خطا',
      subtitle: 'چرا ۱۰۰ کوبیتِ Heron از ۱۰۰۰ کوبیتِ Condor ارزشمندتر است؟',
      summary: 'عبور از سد نویز؛ چطور گوگل و IBM به پایداری کوانتومی دست یافتند.',
      category: 'future',
      categoryName: 'آینده فناوری',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۴/۱۱/۲۵',
      dateEn: '2026-02-14',
      readTime: 15,
      type: 'گزارش ویژه',
      status: 'منتشرشده',
      featured: true,
      tags: ['Quantum', 'IBM', 'Google', 'Physics'],
      diagram: 'quantum',
      views: 5900,
      reactions: 165,
      content: ART10_CONTENT,
      metaDescription: 'تحلیل وضعیت رایانش کوانتومی در سال ۱۴۰۵. بررسی جهش از کوبیت‌های فیزیکی به کوبیت‌های منطقی پایدار و دستاوردهای جدید IBM و گوگل.',
      keywords: ['رایانش کوانتومی', 'IBM Heron', 'اصلاح خطا کوانتومی', 'فناوری آینده', 'فیزیک کوانتوم'],
      canonicalPath: '/article/quantum-computing',
      ogImage: '/images/og/quantum-computing.jpg',
      factCheckedAt: '2026-02-14',
      sourceNotes: 'نشریه Nature Physics و گزارش‌های فنی IBM Quantum',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art11',
      slug: 'microservices-vs-monolith',
      title: 'میکروسرویس یا مونولیت؟ بلوغ معماری در سال ۱۴۰۵',
      subtitle: 'بازگشت مونولیت‌های ماژولار و ظهور ماکروسرویس‌های Wasm',
      summary: 'پایان تعصب معماری؛ چطور بر اساس ابعاد تیم و نیاز بازار بهترین ساختار را انتخاب کنیم؟',
      category: 'software',
      categoryName: 'نرم‌افزار',
      authorId: 'a2',
      authorName: 'سیداحمدرضا محجوب',
      authorUsername: 'ahmadreza-mahjoub',
      date: '۱۴۰۴/۱۱/۱۵',
      dateEn: '2026-02-04',
      readTime: 11,
      type: 'آموزشی',
      status: 'منتشرشده',
      featured: false,
      tags: ['معماری نرم‌افزار', 'Microservices', 'Monolith', 'Wasm'],
      diagram: 'diagram-11',
      views: 3200,
      reactions: 80,
      content: ART11_CONTENT,
      metaDescription: 'مقایسه میکروسرویس و مونولیت در استانداردهای مهندسی سال ۲۰۲۶. چرا بسیاری از تیم‌ها به سمت مونولیت‌های ماژولار و سرویس‌های Wasm بازگشته‌اند؟',
      keywords: ['معماری میکروسرویس', 'مونولیت ماژولار', 'Wasm', 'مهندسی نرم‌افزار', 'طراحی سیستم'],
      canonicalPath: '/article/microservices-vs-monolith',
      ogImage: '/images/og/microservices-vs-monolith.jpg',
      factCheckedAt: '2026-02-04',
      sourceNotes: 'تحلیل‌های High Scalability و تجربیات تیم‌های فنی Netflix و Uber',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art12',
      slug: 'fintech-regulation',
      title: 'تحول فین‌تک و RegTech: نظارت هوشمند بر ریال دیجیتال',
      subtitle: 'نقش هوش مصنوعی در شفافیت مالی و مدیریت ریسک اعتباری',
      summary: 'در سال ۱۴۰۵، اعتماد سنتی جای خود را به اعتماد الگوریتمیک داده است.',
      category: 'startup',
      categoryName: 'استارتاپ',
      authorId: 'a3',
      authorName: 'رادمان قلیچی',
      authorUsername: 'radman-ghelichi',
      date: '۱۴۰۴/۱۱/۰۵',
      dateEn: '2026-01-25',
      readTime: 10,
      type: 'تحلیل اقتصادی',
      status: 'منتشرشده',
      featured: false,
      tags: ['فین‌تک', 'RegTech', 'ریال دیجیتال', 'بانکداری'],
      diagram: 'diagram-12',
      views: 2700,
      reactions: 55,
      content: ART12_CONTENT,
      metaDescription: 'تحلیل تاثیر هوش مصنوعی بر رگولاتوری مالی در سال ۱۴۰۵. بررسی جایگاه ریال دیجیتال و سیستم‌های RegTech در اقتصاد هوشمند ایران.',
      keywords: ['فین‌تک', 'ریال دیجیتال', 'RegTech', 'بانکداری هوشمند', 'اقتصاد ایران'],
      canonicalPath: '/article/fintech-regulation',
      ogImage: '/images/og/fintech-regulation.jpg',
      factCheckedAt: '2026-01-25',
      sourceNotes: 'گزارش‌های بانک مرکزی و پژوهشکده پولی و بانکی',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art13',
      slug: 'llm-security',
      title: 'امنیت مدل‌های زبانی: دفاع در برابر تزریق پرامپت غیرمستقیم',
      subtitle: 'چالش‌های جدید Red Teaming در عصر Claude Opus 4.7',
      summary: 'وقتی هوش مصنوعی به دستورات مخرب پنهان در وب‌سایت‌ها پاسخ می‌دهد.',
      category: 'security',
      categoryName: 'امنیت سایبری',
      authorId: 'a2',
      authorName: 'سیداحمدرضا محجوب',
      authorUsername: 'ahmadreza-mahjoub',
      date: '۱۴۰۴/۱۰/۲۵',
      dateEn: '2026-01-15',
      readTime: 13,
      type: 'امنیت هوش مصنوعی',
      status: 'منتشرشده',
      featured: false,
      tags: ['امنیت', 'LLM', 'Prompt Injection', 'Claude'],
      diagram: 'diagram-13',
      views: 4300,
      reactions: 130,
      content: ART13_CONTENT,
      metaDescription: 'تحلیل حملات تزریق پرامپت غیرمستقیم در سال ۲۰۲۶. راهکارهای امنیتی برای محافظت از مدل‌های زبانی در برابر دستورات مخرب پنهان در داده‌های ورودی.',
      keywords: ['امنیت LLM', 'Prompt Injection', 'Red Teaming', 'امنیت سایبری', 'Claude 4.7'],
      canonicalPath: '/article/llm-security',
      ogImage: '/images/og/llm-security.jpg',
      factCheckedAt: '2026-01-15',
      sourceNotes: 'مستندات OWASP Top 10 for LLMs و گزارش امنیتی Anthropic',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art14',
      slug: 'data-governance-2026',
      title: 'حاکمیت داده در عصر هوش مصنوعی: فراتر از انطباق قانونی',
      subtitle: 'چطور قانون هوش مصنوعی اروپا و فراداده‌های فعال استراتژی ۲۰۲۶ را تغییر می‌دهند؟',
      summary: 'بررسی تحولات حاکمیت داده؛ از نبرد برای شفافیت در EU AI Act تا ظهور فیوزهای قطع‌کننده در عامل‌های هوشمند.',
      category: 'data',
      categoryName: 'علم داده',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۰۵',
      dateEn: '2026-04-25',
      readTime: 13,
      type: 'تحلیل راهبردی',
      status: 'منتشرشده',
      featured: false,
      tags: ['Data Governance', 'EU AI Act', 'Active Metadata', 'Compliance'],
      diagram: 'pipeline',
      views: 3100,
      reactions: 85,
      content: ART14_CONTENT,
      metaDescription: 'تحلیل عمیق حاکمیت داده (Data Governance) در سال ۲۰۲۶. بررسی تاثیر قانون هوش مصنوعی اتحادیه اروپا و مکانیزم‌های نظارت بر عامل‌های خودگردان.',
      keywords: ['حاکمیت داده', 'EU AI Act', 'فراداده فعال', 'هوش مصنوعی', 'امنیت داده'],
      ogImage: '/images/og/data-governance-2026.jpg',
      canonicalPath: '/article/data-governance-2026',
      dateModified: '2026-04-25T09:00:00Z',
      factCheckedAt: '2026-04-25',
      sourceNotes: 'مستندات رسمی کمیسیون اروپا و گزارش‌های حاکمیتی Gartner',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art15',
      slug: 'robotics-warehouse-orchestration',
      title: 'ارکستر رباتیک: وقتی انبارها به شبکه‌های عصبی تبدیل می‌شوند',
      subtitle: 'تقابل ربات‌های انسان‌نما و ناوگان‌های خودمختار در لجستیک ۲۰۲۶',
      summary: 'تحلیل حضور Figure 03 و Amazon Proteus in خطوط تولید؛ چطور مدل‌های VLA درک فیزیکی ماشین‌ها را تغییر دادند.',
      category: 'hardware',
      categoryName: 'سخت‌افزار',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۰۲',
      dateEn: '2026-04-22',
      readTime: 15,
      type: 'بررسی صنعتی',
      status: 'منتشرشده',
      featured: false,
      tags: ['رباتیک', 'لجستیک', 'Amazon Proteus', 'VLA', 'Humanoids'],
      diagram: 'wave',
      views: 4200,
      reactions: 140,
      content: ART15_CONTENT,
      metaDescription: 'بررسی تحول انبارداری هوشمند در سال ۱۴۰۵. تحلیل همکاری ربات‌های انسان‌نما و AMRها در محیط‌های صنعتی و نقش هوش مصنوعی فیزیکی.',
      keywords: ['رباتیک انبار', 'لجستیک هوشمند', 'Tesla Optimus', 'Proteus', 'VLA'],
      ogImage: '/images/og/robotics-warehouse-orchestration.jpg',
      canonicalPath: '/article/robotics-warehouse-orchestration',
      dateModified: '2026-04-22T11:00:00Z',
      factCheckedAt: '2026-04-22',
      sourceNotes: 'گزارش‌های میدانی از دیتاسنترهای آمازون و Agility Robotics',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art16',
      slug: 'open-source-ai-sovereignty',
      title: 'حاکمیت بر هوش: نبرد مدل‌های متن‌باز در برابر باغ‌های محصور',
      subtitle: 'کالبدشکافی لاما ۴ و استانداردهای جدید OSAID در سال ۱۴۰۵',
      summary: 'آیا لاما ۴ واقعاً متن‌باز است؟ بررسی نبرد فلسفی و فنی برای شفافیت در آموزش مدل‌های هوش مصنوعی.',
      category: 'ai',
      categoryName: 'هوش مصنوعی',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۴/۱۲/۲۸',
      dateEn: '2026-03-19',
      readTime: 12,
      type: 'تحلیل فلسفی-فنی',
      status: 'منتشرشده',
      featured: false,
      tags: ['Open Source AI', 'Llama 4', 'OSAID', 'Transparency'],
      diagram: 'diagram-16',
      views: 5600,
      reactions: 190,
      content: ART16_CONTENT,
      metaDescription: 'تحلیل وضعیت هوش مصنوعی متن‌باز در سال ۲۰۲۶. بررسی استاندارد OSAID و تقابل مدل‌های باز مانند Mistral و Llama با مدل‌های اختصاصی.',
      keywords: ['هوش مصنوعی متن باز', 'Llama 4', 'Mistral', 'شفافیت داده', 'OSAID'],
      ogImage: '/images/og/open-source-ai-sovereignty.jpg',
      canonicalPath: '/article/open-source-ai-sovereignty',
      dateModified: '2026-03-19T15:00:00Z',
      factCheckedAt: '2026-03-19',
      sourceNotes: 'بیانیه‌های Open Source Initiative و Meta AI',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art17',
      slug: 'rust-systems-2026',
      title: 'سیستم‌های Rust: ردیابی نفوذ رستم به قلب زیرساخت‌های جهان',
      subtitle: 'بلوغ امنیت حافظه در لینوکس ۶.۱۲ و پایان عصر درایورهای ناایمن',
      summary: 'چطور راست (Rust) از یک زبان آزمایشی به پیش‌نیاز قانونی برای زیرساخت‌های حیاتی در سال ۱۴۰۵ تبدیل شد.',
      category: 'software',
      categoryName: 'نرم‌افزار',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۰۷',
      dateEn: '2026-04-27',
      readTime: 14,
      type: 'تحلیل فنی',
      status: 'منتشرشده',
      featured: false,
      tags: ['Rust', 'Security', 'Linux', 'Memory Safety'],
      diagram: 'diagram-17',
      views: 3400,
      reactions: 110,
      content: ART17_CONTENT,
      metaDescription: 'بررسی وضعیت زبان برنامه‌نویسی Rust در سال ۲۰۲۶. تحلیل نفوذ به هسته لینوکس و ویندوز و تاثیر آن بر امنیت زیرساخت‌های نرم‌افزاری.',
      keywords: ['زبان راست', 'Rust', 'امنیت حافظه', 'برنامه‌نویسی سیستم', 'لینوکس'],
      ogImage: '/images/og/rust-systems-2026.jpg',
      canonicalPath: '/article/rust-systems-2026',
      dateModified: '2026-04-27T10:00:00Z',
      factCheckedAt: '2026-04-27',
      sourceNotes: 'مستندات Kernel.org و گزارش‌های امنیتی CISA',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art18',
      slug: 'venture-capital-ai-2026',
      title: 'سرمایه‌گذاری در هوش مصنوعی: پایان هایپ و آغاز عصر ROI واقعی',
      subtitle: 'کالبدشکافی استراتژی VCها در سال ۱۴۰۵؛ چرا Vertical AI برنده میدان است؟',
      summary: 'تحلیل بازار سرمایه هوش مصنوعی؛ عبور از مدل‌های پایه به سمت ابزارهایی با جاذبه گردش کار (Workflow Gravity).',
      category: 'startup',
      categoryName: 'استارتاپ',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۰۴',
      dateEn: '2026-04-24',
      readTime: 11,
      type: 'تحلیل اقتصادی',
      status: 'منتشرشده',
      featured: false,
      tags: ['VC', 'AI Economy', 'ROI', 'Vertical AI'],
      diagram: 'diagram-18',
      views: 2800,
      reactions: 90,
      content: ART18_CONTENT,
      metaDescription: 'گزارش ویژه از بازار سرمایه‌گذاری هوش مصنوعی در سال ۲۰۲۶. بررسی شاخص‌های جدید ارزیابی استارتاپ‌ها و فرصت‌های اکوسیستم ایران.',
      keywords: ['سرمایه‌گذاری خطرپذیر', 'AI VC', 'ROI هوش مصنوعی', 'Vertical AI', 'استارتاپ'],
      ogImage: '/images/og/venture-capital-ai-2026.jpg',
      canonicalPath: '/article/venture-capital-ai-2026',
      dateModified: '2026-04-24T12:00:00Z',
      factCheckedAt: '2026-04-24',
      sourceNotes: 'تحلیل‌های Crunchbase و گزارش‌های مالی Q1 2026 سیلیکون‌ولی',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art19',
      slug: 'claude-47-opus-reasoning',
      title: 'کلود ۴.۷ اوپوس: کالبدشکافی تفکر تطبیقی و پارامتر xhigh',
      subtitle: 'چطور آنتروپیک با Adaptive Thinking مرزهای استدلال را در سال ۱۴۰۵ جابجا کرد؟',
      summary: 'تحلیل فنی Claude 4.7 Opus؛ مدلی که قبل از حرف زدن فکر می‌کند و رکورددار حل باگ‌های مهندسی است.',
      category: 'ai',
      categoryName: 'هوش مصنوعی',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۱/۳۱',
      dateEn: '2026-04-20',
      readTime: 15,
      type: 'کالبدشکافی فنی',
      status: 'منتشرشده',
      featured: true,
      tags: ['Claude', 'Anthropic', 'Reasoning', 'Adaptive Thinking'],
      diagram: 'brain',
      views: 6300,
      reactions: 215,
      content: ART19_CONTENT,
      metaDescription: 'بررسی تخصصی Claude 4.7 Opus و مکانیزم تفکر تطبیقی. تحلیل بنچمارک‌های SWE-bench و قابلیت‌های بینایی جدید آنتروپیک در سال ۲۰۲۶.',
      keywords: ['Claude 4.7', 'Opus', 'آنتروپیک', 'استدلال هوش مصنوعی', 'تفکر تطبیقی'],
      ogImage: '/images/og/claude-47-opus-reasoning.jpg',
      canonicalPath: '/article/claude-47-opus-reasoning',
      dateModified: '2026-04-20T08:00:00Z',
      factCheckedAt: '2026-04-20',
      sourceNotes: 'گزارش رسمی Anthropic و بنچمارک‌های SWE-bench Verified',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art20',
      slug: 'agentic-ai-production-2026',
      title: 'عصر عامل‌های هوش مصنوعی: چرا AI Agents داغ‌ترین موج فناوری هستند؟',
      subtitle: 'از Copilot تا Coworker؛ همکاران دیجیتال در راهند',
      summary: 'عامل‌های هوشمند نسل بعدی هوش مصنوعی هستند که به جای مشورت، اجرا می‌کنند.',
      category: 'ai',
      categoryName: 'هوش مصنوعی',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۰۹',
      dateEn: '2026-04-30',
      readTime: 16,
      type: 'تحلیل عمیق',
      status: 'منتشرشده',
      featured: false,
      tags: ['AI Agents', 'Agentic AI', 'LLM'],
      diagram: 'neural',
      views: 1200,
      reactions: 45,
      content: ART20_CONTENT,
      metaDescription: 'تحلیل ظهور عامل‌های هوشمند (Agentic AI) در سال ۲۰۲۶؛ بررسی معماری AI Agents، همکاران دیجیتال خودگردان، ابزارخوانی، حافظه کاری و تغییر آینده کار.',
      keywords: ['عامل هوشمند', 'Agentic AI', 'AI Agents', 'خودکارسازی', 'آینده کار'],
      ogImage: '/images/og/agentic-ai-production-2026.jpg',
      canonicalPath: '/article/agentic-ai-production-2026',
      dateModified: '2026-04-30T14:00:00Z',
      factCheckedAt: '2026-04-30',
      sourceNotes: 'پژوهش‌های OpenAI و Microsoft Autonomous Systems',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art21',
      slug: 'vibe-coding-2026',
      title: 'وایب‌کدینگ: وقتی تخیل به سینتکس برتری می‌یابد',
      subtitle: 'آغاز عصر Software 3.0 با هدایت آندره کارپاتی و Cursor AI',
      summary: 'بررسی متدولوژی وایب‌کدینگ؛ چطور در سال ۱۴۰۵ برنامه‌نویسی از نوشتن کد به توصیف نیت تغییر یافت.',
      category: 'software',
      categoryName: 'نرم‌افزار',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۱۸',
      dateEn: '2026-05-08',
      readTime: 12,
      type: 'تحلیل متدولوژی',
      status: 'منتشرشده',
      featured: true,
      tags: ['Vibe Coding', 'Cursor', 'Software 3.0', 'Karpathy'],
      diagram: 'diagram-21',
      views: 4100,
      reactions: 155,
      content: ART21_CONTENT,
      metaDescription: 'تحلیل متدولوژی وایب‌کدینگ (Vibe Coding) در سال ۲۰۲۶. بررسی تاثیر Cursor AI و تغییر نقش برنامه‌نویس به معمار نیت در عصر Software 3.0.',
      keywords: ['وایب کدینگ', 'Vibe Coding', 'Cursor AI', 'آندره کارپاتی', 'برنامه‌نویسی هوشمند'],
      ogImage: '/images/og/vibe-coding-2026.jpg',
      canonicalPath: '/article/vibe-coding-2026',
      dateModified: '2026-05-08T10:00:00Z',
      factCheckedAt: '2026-05-08',
      sourceNotes: 'وبلاگ آندره کارپاتی و گزارش سالانه Cursor 2026',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art22',
      slug: 'ai-energy-crisis-nuclear',
      title: 'بحران انرژی هوش مصنوعی: رنسانس هسته‌ای در دیتاسنترها',
      subtitle: 'چطور SMRها و انرژی اتمی به تنها راه بقای مدل‌های تریلیونی تبدیل شدند؟',
      summary: 'کالبدشکافی مصرف ۵ گیگاواتی دیتاسنترها در سال ۱۴۰۵ و قراردادهای تاریخی مایکروسافت و گوگل با نیروگاه‌های هسته‌ای.',
      category: 'future',
      categoryName: 'آینده فناوری',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۲۰',
      dateEn: '2026-05-10',
      readTime: 14,
      type: 'گزارش ویژه',
      status: 'منتشرشده',
      featured: false,
      tags: ['SMR', 'Energy Crisis', 'Nuclear AI', 'Sustainability'],
      diagram: 'wave',
      views: 3200,
      reactions: 110,
      content: ART22_CONTENT,
      metaDescription: 'بررسی بحران انرژی هوش مصنوعی در سال ۲۰۲۶. تحلیل نقش رآکتورهای کوچک مدولار (SMR) و بازگشت به انرژی هسته‌ای برای تامین برق دیتاسنترهای گیگاواتی.',
      keywords: ['بحران انرژی AI', 'انرژی هسته ای', 'SMR', 'دیتاسنتر', 'پایداری'],
      ogImage: '/images/og/ai-energy-crisis-nuclear.jpg',
      canonicalPath: '/article/ai-energy-crisis-nuclear',
      dateModified: '2026-05-10T08:00:00Z',
      factCheckedAt: '2026-05-10',
      sourceNotes: 'گزارش‌های آژانس بین‌المللی انرژی اتمی و قراردادهای تجاری Big Tech',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art23',
      slug: 'llama-4-open-frontier',
      title: 'لاما ۴ و مرزهای باز: پایان انحصار با معماری Early Fusion',
      subtitle: 'کالبدشکافی Maverick و پنجره زمینه ۱۰ میلیون توکنی در سال ۱۴۰۵',
      summary: 'تحلیل فنی Llama 4؛ مدلی که با معماری بومی چندوجهی و دسترسی باز، توازن قدرت را در دنیای هوش مصنوعی تغییر داد.',
      category: 'ai',
      categoryName: 'هوش مصنوعی',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۲۲',
      dateEn: '2026-05-12',
      readTime: 13,
      type: 'کالبدشکافی فنی',
      status: 'منتشرشده',
      featured: false,
      tags: ['Llama 4', 'Meta AI', 'Open Source', 'Multimodal'],
      diagram: 'diagram-23',
      views: 5800,
      reactions: 195,
      content: ART23_CONTENT,
      metaDescription: 'تحلیل فنی Llama 4 و معماری Early Fusion. بررسی نسخه‌های Maverick و Scout و تاثیر پنجره زمینه ۱۰ میلیون توکنی بر حاکمیت داده در سال ۲۰۲۶.',
      keywords: ['لاما ۴', 'Llama 4', 'Meta AI', 'هوش مصنوعی متن باز', 'Maverick'],
      ogImage: '/images/og/llama-4-open-frontier.jpg',
      canonicalPath: '/article/llama-4-open-frontier',
      dateModified: '2026-05-12T14:00:00Z',
      factCheckedAt: '2026-05-12',
      sourceNotes: 'مستندات فنی Meta Superintelligence Labs',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art24',
      slug: 'deepseek-v4-engram',
      title: 'DeepSeek-V4: پایان انحصار با معماری Engram و حافظه شرطی',
      subtitle: 'چطور حافظه O(1) و مکانیزم MLA اقتصاد هوش مصنوعی را تغییر داد؟',
      summary: 'کالبدشکافی عمیق DeepSeek-V4؛ مدلی که با تفکیک حافظه از استدلال، هزینه‌های استنتاج را به حداقل رساند.',
      category: 'ai',
      categoryName: 'هوش مصنوعی',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۱۵',
      dateEn: '2026-05-05',
      readTime: 14,
      type: 'تحلیل عمیق',
      status: 'منتشرشده',
      featured: true,
      tags: ['DeepSeek', 'MLA', 'Engram', 'MoE'],
      diagram: 'orbit',
      views: 5200,
      reactions: 180,
      content: ART24_CONTENT,
      metaDescription: 'تحلیل فنی DeepSeek-V4 و معماری Engram. بررسی چگونگی کاهش ۱۶ برابری KV Cache با مکانیزم MLA و تاثیر آن بر آینده مدل‌های زبانی متن‌باز.',
      keywords: ['DeepSeek-V4', 'MLA', 'Engram', 'هوش مصنوعی', 'MoE'],
      ogImage: '/images/og/deepseek-v4-engram.jpg',
      canonicalPath: '/article/deepseek-v4-engram',
      dateModified: '2026-05-05T10:00:00Z',
      factCheckedAt: '2026-05-05',
      sourceNotes: 'گزارش فنی DeepSeek AI و تحلیل‌های معماری SemiAnalysis',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art25',
      slug: 'physical-ai-humanoids-2026',
      title: 'هوش مصنوعی فیزیکی: ربات‌های انسان‌نما در آستانه تولید میلیونی',
      subtitle: 'بررسی Figure 03 و تسلا اپتیموس نسل ۳ در خطوط تولید واقعی',
      summary: 'عبور از شبیه‌سازی به واقعیت؛ چطور مدل‌های VLA و World Models باعث جان گرفتن ماشین‌ها در سال ۱۴۰۵ شدند.',
      category: 'hardware',
      categoryName: 'سخت‌افزار',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۱۲',
      dateEn: '2026-05-02',
      readTime: 12,
      type: 'گزارش ویژه',
      status: 'منتشرشده',
      featured: false,
      tags: ['رباتیک', 'Physical AI', 'Tesla Optimus', 'Figure 03'],
      diagram: 'vla',
      views: 3800,
      reactions: 125,
      content: ART25_CONTENT,
      metaDescription: 'بررسی وضعیت تولید ربات‌های انسان‌نما در سال ۲۰۲۶. تحلیل قابلیت‌های تسلا اپتیموس نسل ۳ و ربات Figure 03 در محیط‌های صنعتی و خانگی.',
      keywords: ['ربات انسان‌نما', 'Physical AI', 'Tesla Optimus', 'Figure 03', 'VLA'],
      ogImage: '/images/og/physical-ai-humanoids-2026.jpg',
      canonicalPath: '/article/physical-ai-humanoids-2026',
      dateModified: '2026-05-02T08:00:00Z',
      factCheckedAt: '2026-05-02',
      sourceNotes: 'گزارش‌های مالی تسلا و بازدید از خط تولید BMW',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art26',
      slug: 'post-quantum-cryptography-qday',
      title: 'رمزنگاری پساکوانتومی: زره‌پوشی دنیای دیجیتال در برابر Q-Day',
      subtitle: 'مهاجرت به استانداردهای FIPS 203/204 و امنیت در اوبونتو ۲۶.۰۴',
      summary: 'اینترنت در آستانه تحول؛ بررسی الگوریتم‌های ML-KEM و ML-DSA و ضرورت مهاجرت به PQC برای مقابله با تهدیدات کوانتومی.',
      category: 'security',
      categoryName: 'امنیت سایبری',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۱۰',
      dateEn: '2026-04-30',
      readTime: 11,
      type: 'تحلیل امنیتی',
      status: 'منتشرشده',
      featured: false,
      tags: ['PQC', 'امنیت', 'کوانتوم', 'NIST'],
      diagram: 'cyber',
      views: 2900,
      reactions: 95,
      content: ART26_CONTENT,
      metaDescription: 'راهنمای جامع رمزنگاری پساکوانتومی (PQC). بررسی استانداردهای جدید NIST و نحوه پیاده‌سازی الگوریتم‌های Kyber و Dilithium در زیرساخت‌های مدرن.',
      keywords: ['رمزنگاری پساکوانتومی', 'PQC', 'Q-Day', 'امنیت سایبری', 'NIST'],
      ogImage: '/images/og/post-quantum-cryptography-qday.jpg',
      canonicalPath: '/article/post-quantum-cryptography-qday',
      dateModified: '2026-04-30T14:00:00Z',
      factCheckedAt: '2026-04-30',
      sourceNotes: 'استانداردهای FIPS نهایی شده توسط NIST و مستندات امنیتی Canonical',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art27',
      slug: 'apple-spatial-intelligence-2026',
      title: 'هوش مکانی اپل: کالبدشکافی Siri 2.0 و تراشه A20',
      subtitle: 'چطور اپل شکاف بین پیکسل و اتم را در سال ۱۴۰۵ از بین برد؟',
      summary: 'بررسی استراتژی جدید اپل در Spatial Intelligence؛ از آگاهی روی صفحه تا هدست‌های M5 و Vision Air.',
      category: 'hardware',
      categoryName: 'سخت‌افزار',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۲۵',
      dateEn: '2026-05-15',
      readTime: 14,
      type: 'تحلیل استراتژیک',
      status: 'منتشرشده',
      featured: true,
      tags: ['Apple', 'Vision Pro', 'Spatial Intelligence', 'Siri'],
      diagram: 'vla',
      views: 4200,
      reactions: 185,
      content: ART27_CONTENT,
      metaDescription: 'تحلیل هوش مکانی اپل (Spatial Intelligence) در سال ۲۰۲۶. بررسی قابلیت‌های Siri 2.0، تراشه ۲ نانومتری A20 و آینده رایانش مکانی.',
      keywords: ['اپل', 'Vision Pro', 'Siri 2.0', 'هوش مکانی', 'Spatial Intelligence'],
      ogImage: '/images/og/apple-spatial-intelligence-2026.jpg',
      canonicalPath: '/article/apple-spatial-intelligence-2026',
      dateModified: '2026-05-15T10:00:00Z',
      factCheckedAt: '2026-05-15',
      sourceNotes: 'گزارش‌های زنجیره تامین اپل و تحلیل‌های مینگ-چی کو',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art28',
      slug: 'dna-data-storage-biomemory',
      title: 'ذخیره‌سازی داده روی DNA: رنسانس بیولوژیک در دیتاسنترها',
      subtitle: 'هارد دیسک‌های ابدی؛ پتابایت‌ها در قطره‌ای آب',
      summary: 'کالبدشکافی تکنولوژی DNA Storage در سال ۱۴۰۵؛ چطور Biomemory محدودیت‌های سیلیکون را شکست.',
      category: 'future',
      categoryName: 'آینده فناوری',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۲۸',
      dateEn: '2026-05-18',
      readTime: 15,
      type: 'گزارش فنی',
      status: 'منتشرشده',
      featured: false,
      tags: ['DNA Storage', 'Biomemory', 'Bio-Computing', 'Future'],
      diagram: 'database',
      views: 3100,
      reactions: 140,
      content: ART28_CONTENT,
      metaDescription: 'بررسی تکنولوژی ذخیره‌سازی داده بر پایه DNA در سال ۲۰۲۶. تحلیل سیستم Biomemory Prime و پتانسیل ذخیره کل اینترنت در چند گرم ماده بیولوژیک.',
      keywords: ['DNA Storage', 'ذخیره سازی داده', 'زیست فناوری', 'Biomemory', 'آینده دیتاسنتر'],
      ogImage: '/images/og/dna-data-storage-biomemory.jpg',
      canonicalPath: '/article/dna-data-storage-biomemory',
      dateModified: '2026-05-18T08:00:00Z',
      factCheckedAt: '2026-05-18',
      sourceNotes: 'نشریه Nature Biotechnology و مستندات فنی Biomemory 2026',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art29',
      slug: 'ai-native-operating-systems',
      title: 'سیستم‌عامل‌های نیتیو-هوشمند: تولد هسته AIOS',
      subtitle: 'وقتی مدل زبانی جایگزین CPU می‌شود؛ پایان عصر لینوکس سنتی؟',
      summary: 'تحلیل معماری سیستم‌عامل‌های هوشمند (Agentic OS) در سال ۱۴۰۵ و مدیریت کانتکست در لایه هسته.',
      category: 'software',
      categoryName: 'نرم‌افزار',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۲/۳۰',
      dateEn: '2026-05-20',
      readTime: 13,
      type: 'کالبدشکافی فنی',
      status: 'منتشرشده',
      featured: false,
      tags: ['AIOS', 'Operating System', 'LLM Kernel', 'Windows Intelligence'],
      diagram: 'arch',
      views: 2900,
      reactions: 120,
      content: ART29_CONTENT,
      metaDescription: 'تحلیل معماری سیستم‌عامل‌های AI-Native در سال ۲۰۲۶. بررسی هسته AIOS و نحوه مدیریت عامل‌ها به عنوان فرآیندهای سیستمی خودمختار.',
      keywords: ['سیستم عامل هوشمند', 'AIOS', 'Windows Intelligence', 'هسته سیستم عامل', 'LLM Kernel'],
      ogImage: '/images/og/ai-native-operating-systems.jpg',
      canonicalPath: '/article/ai-native-operating-systems',
      dateModified: '2026-05-20T14:00:00Z',
      factCheckedAt: '2026-05-20',
      sourceNotes: 'پژوهش‌های دانشگاه راتگرز و نقشه‌راه ویندوز ۱۲ مایکروسافت',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art30',
      slug: 'neuromorphic-computing-loihi-3',
      title: 'رایانش نورومورفیک: وقتی سیلیکون به تکامل می‌رسد',
      subtitle: 'کالبدشکافی Intel Loihi 3 و تراشه‌های الهام‌گرفته از مغز',
      summary: 'بررسی تحول پردازش در سال ۱۴۰۵؛ چطور تراشه‌های نورومورفیک با حذف گلوگاه فون نویمان، بهره‌وری انرژی را ۱۰۰۰ برابر افزایش دادند.',
      category: 'hardware',
      categoryName: 'سخت‌افزار',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۳/۰۲',
      dateEn: '2026-05-23',
      readTime: 12,
      type: 'کالبدشکافی فنی',
      status: 'منتشرشده',
      featured: false,
      tags: ['Neuromorphic', 'Loihi 3', 'Intel', 'SNN', 'Edge AI'],
      diagram: 'brain',
      views: 2400,
      reactions: 85,
      content: ART30_CONTENT,
      metaDescription: 'تحلیل رایانش نورومورفیک (Neuromorphic Computing) در سال ۲۰۲۶. بررسی تراشه Intel Loihi 3، مکانیزم Graded Spikes و تاثیر آن بر رباتیک خودمختار.',
      keywords: ['رایانش نورومورفیک', 'Loihi 3', 'شبکه عصبی ضربانی', 'SNN', 'اینتل'],
      ogImage: '/images/og/neuromorphic-computing-loihi-3.jpg',
      canonicalPath: '/article/neuromorphic-computing-loihi-3',
      dateModified: '2026-05-23T10:00:00Z',
      factCheckedAt: '2026-05-23',
      sourceNotes: 'مستندات فنی Intel Labs و گزارش‌های SpiNNcloud Systems',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art31',
      slug: 'orbital-edge-computing-spacex',
      title: 'رایانش لبه‌ای مداری: فرار از بن‌بست انرژی زمین',
      subtitle: 'دیتاسنترهای فضایی؛ وقتی ابرها به فضا می‌روند',
      summary: 'تحلیل استراتژیک دیتاسنترهای مداری در سال ۱۴۰۵؛ بررسی ادغام SpaceX/xAI و آینده اینترنت بدون مرز.',
      category: 'hardware',
      categoryName: 'سخت‌افزار',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۳/۰۵',
      dateEn: '2026-05-26',
      readTime: 14,
      type: 'تحلیل استراتژیک',
      status: 'منتشرشده',
      featured: true,
      tags: ['SpaceX', 'Starlink', 'Orbital Edge', 'Cloud', 'AI'],
      diagram: 'cloud',
      views: 3800,
      reactions: 130,
      content: ART31_CONTENT,
      metaDescription: 'بررسی آینده دیتاسنترهای مداری (Orbital Edge Computing) در سال ۲۰۲۶. تحلیل نقش SpaceX، مایکروسافت Azure Orbital و مزایای انرژی خورشیدی فضایی.',
      keywords: ['رایانش فضایی', 'SpaceX', 'Starlink V3', 'Orbital Edge', 'دیتاسنتر مداری'],
      ogImage: '/images/og/orbital-edge-computing-spacex.jpg',
      canonicalPath: '/article/orbital-edge-computing-spacex',
      dateModified: '2026-05-26T08:00:00Z',
      factCheckedAt: '2026-05-26',
      sourceNotes: 'پرونده‌های FCC اسپیس‌ایکس و گزارش‌های Microsoft Azure Space',
      contentFreshnessStatus: 'current',
    },
    {
      id: 'art32',
      slug: 'graphene-semiconductors-2026',
      title: 'نیمه‌رسانای گرافنی: طلوع عصر پساسیلیکون',
      subtitle: 'تراشه‌های تراهرتزی؛ وقتی کربن جایگزین سیلیکون می‌شود',
      summary: 'کالبدشکافی اولین نیمه‌رسانای کاربردی گرافنی در سال ۱۴۰۵ و پایان ۶۰ سال سلطه سیلیکون بر صنعت الکترونیک.',
      category: 'hardware',
      categoryName: 'سخت‌افزار',
      authorId: 'a1',
      authorName: 'آرسام صباغ',
      authorUsername: 'arsam-sabbagh',
      date: '۱۴۰۵/۰۳/۰۸',
      dateEn: '2026-05-29',
      readTime: 13,
      type: 'کالبدشکافی علمی',
      status: 'منتشرشده',
      featured: false,
      tags: ['Graphene', 'Semiconductor', 'Nano-Electronics', 'SEG', 'Georgia Tech'],
      diagram: 'chip',
      views: 3100,
      reactions: 110,
      content: ART32_CONTENT,
      metaDescription: 'تحلیل فنی نیمه‌رساناهای گرافنی (SEG) در سال ۲۰۲۶. بررسی دستاورد جورجیا تک، تکنولوژی CCS و آینده پردازنده‌های فوق‌سریع کربنی.',
      keywords: ['گرافن', 'نیمه رسانا', 'SEG', 'الکترونیک اتمی', 'جورجیا تک'],
      ogImage: '/images/og/graphene-semiconductors-2026.jpg',
      canonicalPath: '/article/graphene-semiconductors-2026',
      dateModified: '2026-05-29T14:00:00Z',
      factCheckedAt: '2026-05-29',
      sourceNotes: 'پژوهش‌های دانشگاه جورجیا تک و نشریه Nature Electronics',
      contentFreshnessStatus: 'current',
    }
  ];

  const activityLog = [
    { id: 6, user: 'آرسام صباغ', action: 'تحلیل عمیق منتشر کرد', target: 'چرا مدل‌های هوش مصنوعی به داده‌های قابل اعتماد نیاز دارند؟', time: 'اکنون', type: 'publish' },
    { id: 1, user: 'آرسام صباغ', action: 'مقاله جدید منتشر کرد', target: 'عصر عامل‌های هوش مصنوعی', time: '۲ ساعت پیش', type: 'publish' },
    { id: 2, user: 'آرسام صباغ', action: 'مقاله جدید منتشر کرد', target: 'هوش مکانی اپل', time: '۱ ساعت پیش', type: 'publish' },
    { id: 3, user: 'آرسام صباغ', action: 'تحلیل جدید منتشر کرد', target: 'ذخیره‌سازی داده روی DNA', time: '۴۵ دقیقه پیش', type: 'publish' },
    { id: 4, user: 'آرسام صباغ', action: 'کالبدشکافی فنی منتشر کرد', target: 'سیستم‌عامل‌های نیتیو-هوشمند', time: '۱۰ دقیقه پیش', type: 'publish' },
    { id: 5, user: 'آرسام صباغ', action: 'تحلیل علمی منتشر کرد', target: 'نیمه‌رسانای گرافنی', time: '۵ دقیقه پیش', type: 'publish' },
  ];

  const users = [
    { id: 'u1', name: 'آرسام صباغ', username: 'arsam-sabbagh', email: 'arsam@teknav.ir', role: 'writer', status: 'active', articleCount: 24, joindate: '۱۴۰۴/۰۱/۰۱' },
    { id: 'u2', name: 'سیداحمدرضا محجوب', username: 'ahmadreza-mahjoub', email: 'ahmadreza@teknav.ir', role: 'writer', status: 'active', articleCount: 7, joindate: '۱۴۰۴/۰۱/۰۱' },
    { id: 'u3', name: 'رادمان قلیچی', username: 'radman-ghelichi', email: 'radman@teknav.ir', role: 'writer', status: 'active', articleCount: 3, joindate: '۱۴۰۴/۰۱/۰۱' },
  ];

  return { categories, topicHubs, glossary, tags, authors, articles, activityLog, users };
})();
